#!/bin/bash

if [ "$1" == "" ]
then
	echo -e '\e[0;31m#___File Name is Empty___#\e[m'
	exit 1
fi

if [ "$1" == "1" ] || [ "$1" == "2" ] || [ "$1" == "3" ] || [ "$1" == "4" ] || [ "$1" == "5" ]
then
	xclip -o > in$1
	exit 0
fi

if [ "$1" != "" ] && [ "$2" == "" ]
then
	xclip -selection clipboard < $1.cpp
	exit 0
fi

if [ "$1" != "" ] && [ "$2" != "" ]
then
	xclip -o > $1in$2
	exit 0
fi


exit 2
